---
- name: Create Dir for Project
  ansible.builtin.file:
    path: "{{ path_to_remote_directory }}"
    state: directory
    mode: 0755

- name: Git clone
  block:
    - name: Clone repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ path_to_remote_directory }}"
        version: "{{ branch | default('main') }}"
      register: clone_result
      retries: 3
      delay: 5
      until: clone_result is succeeded
