---
- name: Setup sshpass
  ansible.builtin.include_tasks: setup_sshpass.yml

- name: Create Dir for Project
  ansible.builtin.file:
    path: "{{ path_to_remote_directory }}"
    state: directory
    mode: 0755

- name: Sync code
  ansible.posix.synchronize:
    src: "{{ path_to_local_project }}"
    dest: "{{ path_to_remote_directory }}"
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.env"
      - "--exclude=vendor"
      - "--exclude=mode_modules"
