---
- name: Install cerbot
  ansible.builtin.command: snap install --classic certbot
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: Produce Certificates
  ansible.builtin.command:
    argv:
      - /snap/bin/certbot
      - --force-renewal
      - --nginx
      - --noninteractive
      - --agree-tos
      - "--cert-name {{ domain }}"
      - "-d {{ domain }}"
      - -m test@gmail.com
      - --verbose
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
