---
- name: Copy config
  ansible.builtin.template:
    src: ../templates/nginx_conf.j2
    dest: "/etc/nginx/sites-enabled/{{ domain }}"

- name: Reload Nginx
  ansible.builtin.systemd:
    state: reloaded
    name: nginx
