---
- name: Cope config
  ansible.builtin.template:
    src: ../templates/nginx_conf.j2
    dest: "/etc/nginx/sites-enabled/{{ domain }}"

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes
